### PR TITLE
Fix permissions and circus dependency

### PR DESCRIPTION
**Pull request by DeLoWaN**
- Fixed permissions in taiga folder which prevent avatar change and attachments to upload
- Removed circus dependency from pypi (0.12.1) which is not compatible with python3.4.
- Added circus version from github

### CODE REVIEW

**Comment by htdvisser** [comment]
Hi @kalumkalac, thank you for your PR.
- The permissions on the taiga folder have already been fixed in commit 2a60040
- I understand that the circus dependency is a little messy (the taiga guide just suggests installing it with pip2). However, the circus master branch on Github isn't really stable - see [Travis](https://travis-ci.org/circus-tent/circus/branches). Could you `git checkout` a stable tag or commit instead of using the master?

**Comment by DeLoWaN** [comment]
Hello,

The permissions are not enough though. I don't know why since I just discovered Taiga, but without my fix, avatar upload just result in an empty image. Any attachment to a ticket will cause the frontend to throw an error BUT the attachment will be uploaded anyway. [In their doc](https://taigaio.github.io/taiga-doc/dist/setup-production.html), Taiga team suggests that the taiga user should own all the files.

As for circus, the problem is the latest stable release (0.12.1) isn't working with python3.4. Circus 0.12.1 [works with python3.3](http://circus.readthedocs.org/en/latest/installation/). We need that fix : https://github.com/circus-tent/circus/commit/d0d2ac4fd843bb9f050a8c678956fe3682371001, even if the commit message states python3.5. I am getting the same issue that this guy : https://github.com/circus-tent/circus/issues/939 building the image.

Since I am pretty new in the community, I don't know how to handle this.

**Comment by htdvisser** [comment]
To be honest, I created this Docker image when I just discovered Taiga. I actually haven't used it for the last six months, so I'm just keeping this repository up here, but I'm not really maintaining it. 

There could be an issue with your Docker volume permissions, because it is working when I run the image in a container without volumes. The start script fixes this every time the container starts, so I don't understand where it's going wrong.

As far as I remember, circus didn't cause many problems until you submitted your PR, so maybe it works for most users. Then I actually don't think we should change it until circus gets their things right.

**Comment by htdvisser** [comment]
Closing this PR. If anyone else encounters this problem, please reopen.

**Pull request closed without merging**
